/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DocumentChangeInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7418987278153528624L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentChangeInfo\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"fields\":[{\"name\":\"didDocumentChange\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentChangeInfo> ENCODER =
      new BinaryMessageEncoder<DocumentChangeInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentChangeInfo> DECODER =
      new BinaryMessageDecoder<DocumentChangeInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DocumentChangeInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DocumentChangeInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentChangeInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DocumentChangeInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DocumentChangeInfo from a ByteBuffer. */
  public static DocumentChangeInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private boolean didDocumentChange;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentChangeInfo() {}

  /**
   * All-args constructor.
   * @param didDocumentChange The new value for didDocumentChange
   */
  public DocumentChangeInfo(java.lang.Boolean didDocumentChange) {
    this.didDocumentChange = didDocumentChange;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return didDocumentChange;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: didDocumentChange = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'didDocumentChange' field.
   * @return The value of the 'didDocumentChange' field.
   */
  public java.lang.Boolean getDidDocumentChange() {
    return didDocumentChange;
  }


  /**
   * Creates a new DocumentChangeInfo RecordBuilder.
   * @return A new DocumentChangeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder newBuilder() {
    return new com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder();
  }

  /**
   * Creates a new DocumentChangeInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentChangeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder newBuilder(com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder other) {
    return new com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder(other);
  }

  /**
   * Creates a new DocumentChangeInfo RecordBuilder by copying an existing DocumentChangeInfo instance.
   * @param other The existing instance to copy.
   * @return A new DocumentChangeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder newBuilder(com.opentext.bn.converters.avro.entity.DocumentChangeInfo other) {
    return new com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder(other);
  }

  /**
   * RecordBuilder for DocumentChangeInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentChangeInfo>
    implements org.apache.avro.data.RecordBuilder<DocumentChangeInfo> {

    private boolean didDocumentChange;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.didDocumentChange)) {
        this.didDocumentChange = data().deepCopy(fields()[0].schema(), other.didDocumentChange);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentChangeInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.DocumentChangeInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.didDocumentChange)) {
        this.didDocumentChange = data().deepCopy(fields()[0].schema(), other.didDocumentChange);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'didDocumentChange' field.
      * @return The value.
      */
    public java.lang.Boolean getDidDocumentChange() {
      return didDocumentChange;
    }

    /**
      * Sets the value of the 'didDocumentChange' field.
      * @param value The value of 'didDocumentChange'.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder setDidDocumentChange(boolean value) {
      validate(fields()[0], value);
      this.didDocumentChange = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'didDocumentChange' field has been set.
      * @return True if the 'didDocumentChange' field has been set, false otherwise.
      */
    public boolean hasDidDocumentChange() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'didDocumentChange' field.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.DocumentChangeInfo.Builder clearDidDocumentChange() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentChangeInfo build() {
      try {
        DocumentChangeInfo record = new DocumentChangeInfo();
        record.didDocumentChange = fieldSetFlags()[0] ? this.didDocumentChange : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentChangeInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentChangeInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentChangeInfo>
    READER$ = (org.apache.avro.io.DatumReader<DocumentChangeInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
