/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum IntrospectionType {
  INTROSPECTED, GENERATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IntrospectionType\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"symbols\":[\"INTROSPECTED\",\"GENERATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
