/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OwnershipIndicator {
  SENDER, RECEIVER, BOTH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OwnershipIndicator\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"symbols\":[\"SENDER\",\"RECEIVER\",\"BOTH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
