/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TransactionMergeInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2946082063896842557L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionMergeInfo\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"fields\":[{\"name\":\"mergeTransactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionMergeInfo> ENCODER =
      new BinaryMessageEncoder<TransactionMergeInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionMergeInfo> DECODER =
      new BinaryMessageDecoder<TransactionMergeInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TransactionMergeInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TransactionMergeInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionMergeInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TransactionMergeInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TransactionMergeInfo from a ByteBuffer. */
  public static TransactionMergeInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String mergeTransactionId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionMergeInfo() {}

  /**
   * All-args constructor.
   * @param mergeTransactionId The new value for mergeTransactionId
   */
  public TransactionMergeInfo(java.lang.String mergeTransactionId) {
    this.mergeTransactionId = mergeTransactionId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mergeTransactionId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mergeTransactionId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'mergeTransactionId' field.
   * @return The value of the 'mergeTransactionId' field.
   */
  public java.lang.String getMergeTransactionId() {
    return mergeTransactionId;
  }


  /**
   * Creates a new TransactionMergeInfo RecordBuilder.
   * @return A new TransactionMergeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder newBuilder() {
    return new com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder();
  }

  /**
   * Creates a new TransactionMergeInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionMergeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder newBuilder(com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder other) {
    return new com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder(other);
  }

  /**
   * Creates a new TransactionMergeInfo RecordBuilder by copying an existing TransactionMergeInfo instance.
   * @param other The existing instance to copy.
   * @return A new TransactionMergeInfo RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder newBuilder(com.opentext.bn.converters.avro.entity.TransactionMergeInfo other) {
    return new com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder(other);
  }

  /**
   * RecordBuilder for TransactionMergeInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionMergeInfo>
    implements org.apache.avro.data.RecordBuilder<TransactionMergeInfo> {

    private java.lang.String mergeTransactionId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mergeTransactionId)) {
        this.mergeTransactionId = data().deepCopy(fields()[0].schema(), other.mergeTransactionId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionMergeInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.TransactionMergeInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.mergeTransactionId)) {
        this.mergeTransactionId = data().deepCopy(fields()[0].schema(), other.mergeTransactionId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'mergeTransactionId' field.
      * @return The value.
      */
    public java.lang.String getMergeTransactionId() {
      return mergeTransactionId;
    }

    /**
      * Sets the value of the 'mergeTransactionId' field.
      * @param value The value of 'mergeTransactionId'.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder setMergeTransactionId(java.lang.String value) {
      validate(fields()[0], value);
      this.mergeTransactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mergeTransactionId' field has been set.
      * @return True if the 'mergeTransactionId' field has been set, false otherwise.
      */
    public boolean hasMergeTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mergeTransactionId' field.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.TransactionMergeInfo.Builder clearMergeTransactionId() {
      mergeTransactionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionMergeInfo build() {
      try {
        TransactionMergeInfo record = new TransactionMergeInfo();
        record.mergeTransactionId = fieldSetFlags()[0] ? this.mergeTransactionId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionMergeInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionMergeInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionMergeInfo>
    READER$ = (org.apache.avro.io.DatumReader<TransactionMergeInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
